(when (fboundp 'rtags-find-file)
  (defun rtags-hook ()
    (spacemacs/declare-prefix "R" "Rtags")
    (spacemacs/set-leader-keys "Rs" 'rtags-find-symbol)
    (spacemacs/set-leader-keys "Rg" 'rtags-find-symbol-at-point)
    (spacemacs/set-leader-keys "Rh" 'rtags-location-stack-back)
    (spacemacs/set-leader-keys "Rl" 'rtags-location-stack-forward)
    (spacemacs/set-leader-keys "Ri" 'rtags-imenu))
  (add-hook 'c-mode-common-hook 'rtags-hook)
  )
