(when (fboundp 'rtags-find-file)
  (defun rtags-keybindings (mode)
    (spacemacs/set-leader-keys-for-major-mode mode "s" 'rtags-find-symbol)
    (spacemacs/set-leader-keys-for-major-mode mode "R" 'rtags-imenu)
    (spacemacs/set-leader-keys-for-major-mode mode "p" 'rtags-preprocess-file)
    (spacemacs/set-leader-keys-for-major-mode mode "f" 'rtags-fixit)
    )
  (defun rtags-hook ()
    (rtags-keybindings 'c-mode)
    (rtags-keybindings 'c++-mode)
    (rtags-keybindings 'objc-mode)
    (add-to-list 'spacemacs-jump-handlers-c-mode
                 '(rtags-find-symbol-at-point :async t))
    (add-to-list 'spacemacs-jump-handlers-c++-mode
                 '(rtags-find-symbol-at-point :async t)))
  (add-hook 'c-mode-common-hook 'rtags-hook))
